import {
  Button,
  Cell,
  CellGroup,
  Icon,
  Image as VanImage,
  Col,
  Row,
  Popup,
  Toast,
  Calendar,
  Cascader,
  Checkbox,
  CheckboxGroup,
  DatetimePicker,
  Field,
  Form,
  NumberKeyboard,
  PasswordInput,
  Picker,
  RadioGroup,
  Radio,
  Rate,
  Search,
  Slider,
  Stepper,
  Switch,
  Uploader,
  ActionSheet,
  Dialog,
  DropdownMenu,
  DropdownItem,
  Loading,
  Notify,
  Overlay,
  PullRefresh,
  ShareSheet,
  SwipeCell,
  Badge,
  Circle,
  Collapse,
  CollapseItem,
  CountDown,
  Divider,
  Empty,
  ImagePreview,
  Lazyload,
  List,
  NoticeBar,
  Popover,
  Progress,
  Skeleton,
  Step,
  Steps,
  Sticky,
  Swipe,
  SwipeItem,
  Tag,
  // ActionBar,
  // ActionBarIcon,
  // ActionBarButton,
  Grid,
  GridItem,
  IndexBar,
  IndexAnchor,
  NavBar,
  Pagination,
  Sidebar,
  SidebarItem,
  Tab,
  Tabs,
  Tabbar,
  TabbarItem,
  TreeSelect
} from "vant";

export const loadComponents = function(app) {
  app.use(Button);
  app.use(Cell);
  app.use(CellGroup);
  app.use(Icon);
  app.use(VanImage);
  app.use(Col);
  app.use(Row);
  app.use(Popup);
  app.use(Toast);
  app.use(Calendar);
  app.use(Cascader);
  app.use(Checkbox);
  app.use(CheckboxGroup);
  app.use(DatetimePicker);
  app.use(Field);
  app.use(Form);
  app.use(NumberKeyboard);
  app.use(PasswordInput);
  app.use(Picker);
  app.use(RadioGroup);
  app.use(Radio);
  app.use(Rate);
  app.use(Search);
  app.use(Slider);
  app.use(Stepper);
  app.use(Switch);
  app.use(Uploader);
  app.use(ActionSheet);
  app.use(Dialog);
  app.use(DropdownMenu);
  app.use(DropdownItem);
  app.use(Loading);
  app.use(Notify);
  app.use(Overlay);
  app.use(PullRefresh);
  app.use(ShareSheet);
  app.use(SwipeCell);
  app.use(Badge);
  app.use(Circle);
  app.use(Collapse);
  app.use(CollapseItem);
  app.use(CountDown);
  app.use(Divider);
  app.use(Empty);
  app.use(ImagePreview);
  app.use(Lazyload);
  app.use(List);
  app.use(NoticeBar);
  app.use(Popover);
  app.use(Progress);
  app.use(Skeleton);
  app.use(Step);
  app.use(Steps);
  app.use(Sticky);
  app.use(Swipe);
  app.use(SwipeItem);
  app.use(Tag);
  // app.use(ActionBar);
  // app.use(ActionBarIcon);
  // app.use(ActionBarButton);
  app.use(Grid);
  app.use(GridItem);
  app.use(IndexBar);
  app.use(IndexAnchor);
  app.use(NavBar);
  app.use(Pagination);
  app.use(Sidebar);
  app.use(SidebarItem);
  app.use(Tab);
  app.use(Tabs);
  app.use(Tabbar);
  app.use(TabbarItem);
  app.use(TreeSelect);
};
